# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.0b1-1-g5106f80
_src_path: ../ioc-template
description: The simulation AreaDetector
git_platform: github.com
github_org: epics-containers
name: ioc-adsimdetector
repo_uri: git@github.com:epics-containers/ioc-adsimdetector.git
rtems: false
