# yaml-language-server: $schema=/epics/ibek-defs/ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: Example simulated camera

entities:
  - type: autosave.Autosave
    settings_req_period: 10
    P: "BL01T-EA-TST-02:"

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADSimDetector.simDetector
    PORT: DET.DET
    P: BL01T-EA-TST-02
    R: ":DET:"
    # DATATYPE:0 = Int8 - TODO add an enum to the support yaml
    DATATYPE: 0
    WIDTH: 1024
    HEIGHT: 1024

  - type: epics.PostStartupCommand
    command: |
      dbpf BL01T-EA-TST-02:DET:AcquireTime 0.1
      dbpf BL01T-EA-TST-02:ARR:EnableCallbacks 1
      dbpf BL01T-EA-TST-02:PROC:EnableCallbacks 1
      dbpf BL01T-EA-TST-02:ROI:EnableCallbacks 1
      dbpf BL01T-EA-TST-02:PVA:EnableCallbacks 1
      dbpf BL01T-EA-TST-02:DET:Acquire 1

  - type: ADCore.NDROI
    PORT: DET.ROI
    P: BL01T-EA-TST-02
    R: ":ROI:"
    NDARRAY_PORT: DET.DET

  - type: ADCore.NDProcess
    PORT: DET.PROC
    P: BL01T-EA-TST-02
    R: ":PROC:"
    NDARRAY_PORT: DET.ROI

  - type: ADCore.NDPvaPlugin
    PORT: DET.PVA
    PVNAME: BL01T-EA-TST-02:PVA:OUTPUT
    P: BL01T-EA-TST-02
    R: ":PVA:"
    NDARRAY_PORT: DET.DET

  - type: ADCore.NDStdArrays
    PORT: DET.ARR
    P: BL01T-EA-TST-02
    R: ":ARR:"
    NDARRAY_PORT: DET.PROC
    TYPE: Int8
    NELEMENTS: 1048576
    FTVL: CHAR

  - type: ADCore.NDStats
    PORT: DET.STAT
    P: BL01T-EA-TST-02
    R: ":STAT:"
    NDARRAY_PORT: DET.DET
    XSIZE: 1024
    YSIZE: 1024
    HIST_SIZE: 20

  - type: ADCore.NDFileHDF5
    PORT: DET.HDF
    P: BL01T-EA-TST-02
    R: ":HDF:"
    NDARRAY_PORT: DET.PROC

  - type: ADCore.NDFileTIFF
    PORT: DET.TIFF
    P: BL01T-EA-TST-02
    R: ":TIFF:"
    NDARRAY_PORT: DET.PROC

  - type: ADCore.NDOverlay
    PORT: DET.OVER
    P: BL01T-EA-TST-02
    R: ":OVER:"
    NDARRAY_PORT: DET.PROC
