# NOTE: port numbers are defaults only
# this script to be processed with sed to replace port numbers
# see phoebus-launch.sh

# using broadcast ports for this devcontainer
# deliberately set to unused values so that we don't need to use the
# defunct org.phoebus.pv.ca/auto_addr_list=false
org.phoebus.pv.ca/server_port=10064
org.phoebus.pv.ca/repeater_port=10065
org.phoebus.pv.pva/epics_pva_broadcast_port=10076

# point ca and pva to localhost
org.phoebus.pv.ca/name_servers=127.0.0.1:5064
org.phoebus.pv.pva/epics_pva_name_servers=127.0.0.1:5076

# turn off auto address list to avoid picking up other workstations on the network
# this is the correct way to disable auto address list for both ca and pva
# BUT this breaks phoebus 5.0.2 so leave commented out
# org.phoebus.pv.ca/auto_addr_list=false
# org.phoebus.pv.pva/epics_pva_auto_addr_list=false